import type { MealType, Recipe } from "@/src/lib/recipes/types";

export type { MealType, Recipe } from "@/src/lib/recipes/types";

export const recipes: Recipe[] = [
  {
    slug: "greek-yogurt-protein-bowl",
    title: "Greek Yogurt Protein Bowl",
    mealType: "Breakfast",
    goals: ["Fat loss", "High protein", "Quick"],
    description:
      "A fast protein-heavy breakfast bowl with fruit, oats, and peanut butter.",
    ingredients: [
      "Greek yogurt",
      "Banana",
      "Berries",
      "Peanut butter",
      "Oats",
      "Cinnamon",
    ],
    calories: 420,
    protein: 32,
    carbs: 48,
    fat: 12,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Add Greek yogurt to a bowl.",
      "Slice banana and add berries.",
      "Add oats and peanut butter.",
      "Finish with cinnamon.",
    ],
    tags: ["Breakfast", "Fruit", "No cook", "High protein"],
  },
  {
    slug: "yogurt-berry-banana-crunch",
    title: "Yogurt, Berry & Banana Crunch",
    mealType: "Breakfast",
    goals: ["Get fit", "Quick", "High protein"],
    description:
      "A generous fruit-and-yogurt breakfast with enough crunch and carbohydrate to feel like a real meal.",
    ingredients: [
      "250g plain 2% Greek yogurt",
      "1 medium banana",
      "100g mixed berries",
      "20g granola",
      "10g honey",
      "Cinnamon",
    ],
    calories: 455,
    protein: 28,
    carbs: 70,
    fat: 7,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Spoon the yogurt into a breakfast bowl.",
      "Slice the banana and scatter it over the yogurt with the berries.",
      "Top with granola, honey, and cinnamon just before eating.",
    ],
    tags: ["Breakfast", "Fruit", "No cook", "Yogurt"],
  },
  {
    slug: "eggs-avocado-toast",
    title: "Eggs, Avocado & Toast",
    mealType: "Breakfast",
    goals: ["Get fit", "Balanced", "Quick"],
    description:
      "A simple whole-food breakfast with eggs, avocado, toast, and tomatoes.",
    ingredients: [
      "Eggs",
      "Avocado",
      "Wholegrain toast",
      "Mini tomatoes",
      "Salt",
      "Pepper",
    ],
    calories: 480,
    protein: 25,
    carbs: 38,
    fat: 26,
    prepTimeMinutes: 5,
    cookTimeMinutes: 10,
    difficulty: "Easy",
    instructions: [
      "Cook eggs to preference.",
      "Toast the bread.",
      "Slice avocado and tomatoes.",
      "Plate together and season.",
    ],
    tags: ["Breakfast", "Balanced", "Whole foods"],
  },
  {
    slug: "steak-egg-breakfast-plate",
    title: "Steak & Egg Breakfast Plate",
    mealType: "Breakfast",
    goals: ["Muscle gain", "High protein"],
    description: "A high-protein breakfast plate for heavier training days.",
    ingredients: ["Lean steak", "Eggs", "Mushrooms", "Mini tomatoes", "Spinach"],
    calories: 560,
    protein: 48,
    carbs: 12,
    fat: 34,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "Medium",
    instructions: [
      "Season and cook steak.",
      "Cook eggs to preference.",
      "Saute mushrooms, tomatoes, and spinach.",
      "Serve together.",
    ],
    tags: ["Breakfast", "High protein", "Training day"],
  },
  {
    slug: "banana-peanut-butter-oats",
    title: "Banana Peanut Butter Oats",
    mealType: "Breakfast",
    goals: ["Budget", "Get fit"],
    description: "Budget-friendly oats for energy and satiety.",
    ingredients: ["Oats", "Banana", "Peanut butter", "Milk", "Cinnamon"],
    calories: 520,
    protein: 22,
    carbs: 70,
    fat: 18,
    prepTimeMinutes: 3,
    cookTimeMinutes: 5,
    difficulty: "Easy",
    instructions: [
      "Cook oats with milk.",
      "Stir in peanut butter.",
      "Top with sliced banana and cinnamon.",
    ],
    tags: ["Breakfast", "Budget", "Oats"],
  },
  {
    slug: "high-protein-smoothie",
    title: "High-Protein Smoothie",
    mealType: "Breakfast",
    goals: ["Quick", "High protein", "Get fit"],
    description: "A quick smoothie for busy mornings.",
    ingredients: ["Greek yogurt", "Banana", "Oats", "Peanut butter", "Milk", "Ice"],
    calories: 500,
    protein: 35,
    carbs: 58,
    fat: 15,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Add all ingredients to blender.",
      "Blend until smooth.",
      "Serve cold.",
    ],
    tags: ["Breakfast", "Smoothie", "Quick"],
  },
  {
    slug: "cottage-cheese-fruit-bowl",
    title: "Cottage Cheese Fruit Bowl",
    mealType: "Breakfast",
    goals: ["Fat loss", "Quick", "High protein"],
    description: "A light high-protein breakfast or snack bowl.",
    ingredients: ["Cottage cheese", "Apple", "Berries", "Honey", "Cinnamon"],
    calories: 330,
    protein: 28,
    carbs: 38,
    fat: 7,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Add cottage cheese to a bowl.",
      "Add sliced apple and berries.",
      "Add a small drizzle of honey.",
      "Finish with cinnamon.",
    ],
    tags: ["Breakfast", "No cook", "High protein"],
  },
  {
    slug: "chicken-rice-power-bowl",
    title: "Chicken Rice Power Bowl",
    mealType: "Lunch",
    goals: ["Fat loss", "Meal prep", "High protein"],
    description:
      "A balanced chicken and rice bowl with vegetables and avocado.",
    ingredients: ["Chicken breast", "Rice", "Peas", "Corn", "Tomatoes", "Avocado"],
    calories: 620,
    protein: 45,
    carbs: 68,
    fat: 18,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: "Easy",
    instructions: [
      "Cook rice.",
      "Grill or pan-cook chicken.",
      "Add peas, corn, tomatoes, and avocado.",
      "Slice chicken and serve over rice.",
    ],
    tags: ["Lunch", "Meal prep", "Chicken"],
  },
  {
    slug: "chicken-salad-wrap",
    title: "Chicken Salad Wrap",
    mealType: "Lunch",
    goals: ["Quick", "High protein"],
    description:
      "A quick wrap with chicken, salad vegetables, and a light dressing.",
    ingredients: [
      "Chicken breast",
      "Wholewheat wrap",
      "Lettuce",
      "Tomato",
      "Shredded cabbage",
      "Avocado or Greek yogurt dressing",
    ],
    calories: 470,
    protein: 38,
    carbs: 42,
    fat: 15,
    prepTimeMinutes: 10,
    cookTimeMinutes: 5,
    difficulty: "Easy",
    instructions: [
      "Slice cooked chicken.",
      "Add salad ingredients to wrap.",
      "Add avocado or Greek yogurt dressing.",
      "Roll and serve.",
    ],
    tags: ["Lunch", "Wrap", "Quick"],
  },
  {
    slug: "steak-potato-meal-prep",
    title: "Steak & Potato Meal Prep",
    mealType: "Lunch",
    goals: ["Muscle gain", "Meal prep", "High protein"],
    description:
      "A filling meal-prep option with steak, potatoes, and vegetables.",
    ingredients: ["Lean steak", "Potatoes", "Peas", "Mushrooms", "Tomatoes"],
    calories: 680,
    protein: 50,
    carbs: 62,
    fat: 24,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: "Medium",
    instructions: [
      "Cook potatoes.",
      "Cook steak to preference.",
      "Saute mushrooms, peas, and tomatoes.",
      "Portion into meal-prep containers.",
    ],
    tags: ["Lunch", "Meal prep", "Muscle gain"],
  },
  {
    slug: "chicken-avocado-salad",
    title: "Chicken Avocado Salad",
    mealType: "Lunch",
    goals: ["Fat loss", "Low carb", "High protein"],
    description: "A fresh chicken salad with avocado and vegetables.",
    ingredients: [
      "Chicken breast",
      "Avocado",
      "Lettuce",
      "Tomato",
      "Red pepper",
      "Olive oil dressing",
    ],
    calories: 520,
    protein: 42,
    carbs: 18,
    fat: 30,
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "Easy",
    instructions: [
      "Cook and slice chicken.",
      "Add salad vegetables to bowl.",
      "Add avocado.",
      "Top with chicken and dressing.",
    ],
    tags: ["Lunch", "Salad", "Low carb"],
  },
  {
    slug: "egg-fried-rice-vegetables",
    title: "Egg Fried Rice with Vegetables",
    mealType: "Lunch",
    goals: ["Budget", "Balanced"],
    description: "A budget-friendly rice dish with eggs and vegetables.",
    ingredients: ["Rice", "Eggs", "Peas", "Corn", "Carrots", "Spring onion", "Soy sauce"],
    calories: 560,
    protein: 24,
    carbs: 78,
    fat: 16,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "Easy",
    instructions: [
      "Cook eggs in pan.",
      "Add cooked rice and vegetables.",
      "Add soy sauce.",
      "Stir-fry until hot.",
    ],
    tags: ["Lunch", "Budget", "Balanced"],
  },
  {
    slug: "mince-rice-bowl",
    title: "Mince & Rice Bowl",
    mealType: "Lunch",
    goals: ["Meal prep", "High protein"],
    description: "A simple lean mince bowl for meal prep.",
    ingredients: ["Lean mince", "Rice", "Tomatoes", "Onion", "Peas", "Spices"],
    calories: 650,
    protein: 42,
    carbs: 70,
    fat: 20,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: "Easy",
    instructions: [
      "Cook rice.",
      "Cook mince with onion, tomatoes, peas, and spices.",
      "Serve mince mixture over rice.",
    ],
    tags: ["Lunch", "Meal prep", "Mince"],
  },
  {
    slug: "chicken-satay-noodle-bowl",
    title: "Chicken Satay Noodle Bowl",
    mealType: "Lunch",
    goals: ["High protein", "Meal prep"],
    description:
      "Tender chicken, egg noodles, crunchy vegetables, and a measured peanut-lime sauce.",
    ingredients: [
      "150g cooked chicken breast",
      "75g dry egg noodles",
      "100g stir-fry vegetables",
      "15g peanut butter",
      "1 tsp soy sauce",
      "Lime juice",
      "Chilli flakes",
    ],
    calories: 640,
    protein: 48,
    carbs: 73,
    fat: 17,
    prepTimeMinutes: 10,
    cookTimeMinutes: 12,
    difficulty: "Easy",
    instructions: [
      "Cook the noodles according to the packet and drain.",
      "Stir-fry the vegetables and sliced chicken until hot.",
      "Loosen the peanut butter with soy sauce, lime juice, chilli, and a splash of hot water.",
      "Toss everything together and serve.",
    ],
    tags: ["Lunch", "Noodles", "Chicken", "Meal prep"],
  },
  {
    slug: "beef-broccoli-ramen",
    title: "Beef & Broccoli Ramen",
    mealType: "Lunch",
    goals: ["Muscle gain", "High protein"],
    description:
      "A proper ramen-style lunch with lean beef, broccoli, mushrooms, and a savoury broth.",
    ingredients: [
      "140g lean beef strips",
      "85g dry ramen noodles",
      "120g broccoli",
      "80g mushrooms",
      "300ml low-sodium beef stock",
      "1 tsp sesame oil",
      "Soy sauce, garlic, and ginger",
    ],
    calories: 680,
    protein: 45,
    carbs: 75,
    fat: 22,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "Medium",
    instructions: [
      "Sear the beef strips quickly and set aside.",
      "Simmer the stock with garlic, ginger, broccoli, and mushrooms.",
      "Cook the noodles in the broth until tender.",
      "Return the beef, add soy sauce and sesame oil, and serve immediately.",
    ],
    tags: ["Lunch", "Noodles", "Beef", "Comfort food"],
  },
  {
    slug: "chilli-garlic-prawn-noodles",
    title: "Chilli Garlic Prawn Noodles",
    mealType: "Lunch",
    goals: ["Quick", "High protein"],
    description:
      "Juicy prawns and springy noodles in a punchy garlic-chilli sauce with plenty of vegetables.",
    ingredients: [
      "180g peeled prawns",
      "80g dry wheat noodles",
      "150g mixed stir-fry vegetables",
      "2 tsp cooking oil",
      "1 tbsp soy sauce",
      "Garlic, fresh chilli, and lime",
    ],
    calories: 630,
    protein: 45,
    carbs: 76,
    fat: 16,
    prepTimeMinutes: 10,
    cookTimeMinutes: 10,
    difficulty: "Easy",
    instructions: [
      "Cook and drain the noodles.",
      "Stir-fry the prawns in half the oil until just cooked, then set aside.",
      "Cook the vegetables, garlic, and chilli in the remaining oil.",
      "Add the noodles, prawns, soy sauce, and lime, then toss well.",
    ],
    tags: ["Lunch", "Noodles", "Seafood", "Quick"],
  },
  {
    slug: "sesame-tofu-soba-bowl",
    title: "Sesame Tofu Soba Bowl",
    mealType: "Lunch",
    goals: ["Meal prep", "Balanced"],
    description:
      "Crisp tofu, nutty soba noodles, edamame, and vegetables with a sesame dressing.",
    ingredients: [
      "180g firm tofu",
      "80g dry soba noodles",
      "60g shelled edamame",
      "120g shredded vegetables",
      "1 tbsp sesame dressing",
      "Spring onion and sesame seeds",
    ],
    calories: 640,
    protein: 30,
    carbs: 75,
    fat: 24,
    prepTimeMinutes: 12,
    cookTimeMinutes: 12,
    difficulty: "Easy",
    instructions: [
      "Cook the soba noodles, rinse briefly, and drain well.",
      "Pat the tofu dry, cube it, and pan-sear until golden.",
      "Combine the noodles, tofu, edamame, and vegetables.",
      "Toss with sesame dressing and finish with spring onion and sesame seeds.",
    ],
    tags: ["Lunch", "Noodles", "Vegetarian", "Meal prep"],
  },
  {
    slug: "tuna-edamame-noodle-salad",
    title: "Tuna Edamame Noodle Salad",
    mealType: "Lunch",
    goals: ["High protein", "Meal prep", "Quick"],
    description:
      "A chilled rice-noodle lunch with tuna, edamame, crisp vegetables, and ginger-lime dressing.",
    ingredients: [
      "1 x 170g can tuna in spring water, drained",
      "75g dry rice noodles",
      "70g shelled edamame",
      "120g carrot, cabbage, and sugar snap peas",
      "1 tbsp ginger-lime dressing",
      "Fresh coriander",
    ],
    calories: 625,
    protein: 42,
    carbs: 78,
    fat: 16,
    prepTimeMinutes: 12,
    cookTimeMinutes: 5,
    difficulty: "Easy",
    instructions: [
      "Soak or cook the rice noodles, then rinse cold and drain.",
      "Flake the drained tuna into a large bowl.",
      "Add noodles, edamame, vegetables, and coriander.",
      "Toss with the ginger-lime dressing and chill until needed.",
    ],
    tags: ["Lunch", "Noodles", "Tuna", "Meal prep"],
  },
  {
    slug: "biltong-chilli-crisp-noodles",
    title: "Biltong Chilli-Crisp Noodles",
    mealType: "Lunch",
    goals: ["High protein", "Quick"],
    description:
      "A South African-inspired noodle bowl with sliced biltong, egg, greens, and restrained chilli crisp.",
    ingredients: [
      "50g lean sliced biltong",
      "75g dry egg noodles",
      "1 large egg",
      "120g pak choi or spinach",
      "2 tsp chilli crisp",
      "1 tsp soy sauce",
      "Spring onion",
    ],
    calories: 585,
    protein: 39,
    carbs: 68,
    fat: 17,
    prepTimeMinutes: 8,
    cookTimeMinutes: 10,
    difficulty: "Easy",
    instructions: [
      "Cook and drain the egg noodles.",
      "Soft-boil or fry the egg to preference.",
      "Wilt the greens with soy sauce, then toss through the noodles and chilli crisp.",
      "Top with the egg, sliced biltong, and spring onion; do not cook the biltong further.",
    ],
    tags: ["Lunch", "Noodles", "Biltong", "Quick"],
  },
  {
    slug: "chicken-stir-fry",
    title: "Chicken Stir Fry",
    mealType: "Dinner",
    goals: ["Fat loss", "Balanced", "Quick"],
    description:
      "A balanced chicken stir fry with vegetables and rice or noodles.",
    ingredients: ["Chicken breast", "Mixed vegetables", "Rice or noodles", "Garlic", "Soy sauce"],
    calories: 580,
    protein: 45,
    carbs: 65,
    fat: 14,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "Easy",
    instructions: [
      "Cook rice or noodles.",
      "Stir-fry chicken with garlic.",
      "Add vegetables and soy sauce.",
      "Serve together.",
    ],
    tags: ["Dinner", "Quick", "Balanced"],
  },
  {
    slug: "salmon-sweet-potato",
    title: "Salmon & Sweet Potato",
    mealType: "Dinner",
    goals: ["Recovery", "Healthy fats", "High protein"],
    description: "A recovery-focused dinner with salmon and sweet potato.",
    ingredients: ["Salmon", "Sweet potato", "Green vegetables", "Lemon", "Olive oil"],
    calories: 650,
    protein: 42,
    carbs: 52,
    fat: 28,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: "Medium",
    instructions: [
      "Roast or boil sweet potato.",
      "Cook salmon with lemon and seasoning.",
      "Steam or saute green vegetables.",
      "Plate together.",
    ],
    tags: ["Dinner", "Recovery", "Healthy fats"],
  },
  {
    slug: "lean-beef-mince-bolognese",
    title: "Lean Beef Mince Bolognese",
    mealType: "Dinner",
    goals: ["High protein", "Balanced"],
    description:
      "A high-protein comfort meal using lean mince and tomato sauce.",
    ingredients: ["Lean mince", "Tomato sauce", "Pasta", "Mushrooms", "Onion"],
    calories: 700,
    protein: 45,
    carbs: 82,
    fat: 20,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: "Easy",
    instructions: [
      "Cook pasta.",
      "Cook mince with onion and mushrooms.",
      "Add tomato sauce.",
      "Serve sauce over pasta.",
    ],
    tags: ["Dinner", "Comfort food", "High protein"],
  },
  {
    slug: "steak-eggs-vegetables",
    title: "Steak, Eggs & Vegetables",
    mealType: "Dinner",
    goals: ["High protein", "Low carb"],
    description:
      "A simple high-protein dinner with steak, eggs, and vegetables.",
    ingredients: ["Steak", "Eggs", "Mushrooms", "Tomatoes", "Spinach"],
    calories: 620,
    protein: 55,
    carbs: 14,
    fat: 36,
    prepTimeMinutes: 10,
    cookTimeMinutes: 15,
    difficulty: "Medium",
    instructions: [
      "Cook steak to preference.",
      "Cook eggs.",
      "Saute mushrooms, tomatoes, and spinach.",
      "Serve together.",
    ],
    tags: ["Dinner", "Low carb", "High protein"],
  },
  {
    slug: "chicken-potato-veg-tray-bake",
    title: "Chicken, Potato & Veg Tray Bake",
    mealType: "Dinner",
    goals: ["Meal prep", "Easy dinner"],
    description: "A simple tray bake that works well for batch cooking.",
    ingredients: ["Chicken thighs or breast", "Potatoes", "Carrots", "Onion", "Spices"],
    calories: 670,
    protein: 48,
    carbs: 60,
    fat: 24,
    prepTimeMinutes: 10,
    cookTimeMinutes: 35,
    difficulty: "Easy",
    instructions: [
      "Add chicken, potatoes, carrots, and onion to a tray.",
      "Season with spices.",
      "Bake until cooked through.",
      "Serve hot or portion for meal prep.",
    ],
    tags: ["Dinner", "Meal prep", "Tray bake"],
  },
  {
    slug: "chicken-burger-bowl",
    title: "Chicken Burger Bowl",
    mealType: "Dinner",
    goals: ["Healthy comfort food", "High protein"],
    description: "A burger-style bowl without the heavy fast-food feel.",
    ingredients: ["Lean chicken patty", "Lettuce", "Tomato", "Potato wedges", "Greek yogurt sauce"],
    calories: 620,
    protein: 44,
    carbs: 55,
    fat: 22,
    prepTimeMinutes: 10,
    cookTimeMinutes: 20,
    difficulty: "Easy",
    instructions: [
      "Cook chicken patty.",
      "Bake potato wedges.",
      "Add lettuce and tomato to bowl.",
      "Add chicken and yogurt sauce.",
    ],
    tags: ["Dinner", "Comfort food", "High protein"],
  },
  {
    slug: "chicken-korma-garlic-naan",
    title: "Chicken Korma & Garlic Naan",
    mealType: "Dinner",
    goals: ["High protein", "Healthy comfort food"],
    description:
      "A creamy, gently spiced chicken korma with a full naan portion and a realistic amount of sauce.",
    ingredients: [
      "170g chicken breast",
      "1 medium garlic naan",
      "100ml light coconut milk",
      "40g plain Greek yogurt",
      "15g ground almonds",
      "Onion, garlic, ginger, and korma spices",
      "Fresh coriander",
    ],
    calories: 780,
    protein: 48,
    carbs: 82,
    fat: 29,
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: "Medium",
    instructions: [
      "Cook the onion, garlic, ginger, and korma spices until fragrant.",
      "Add cubed chicken and cook until lightly coloured.",
      "Stir in coconut milk and ground almonds, then simmer until the chicken is cooked through.",
      "Remove from direct heat, stir in the yogurt, and serve with warmed garlic naan and coriander.",
    ],
    tags: ["Dinner", "Indian", "Chicken", "Naan"],
  },
  {
    slug: "chicken-tikka-masala-rice",
    title: "Chicken Tikka Masala & Basmati Rice",
    mealType: "Dinner",
    goals: ["High protein", "Meal prep"],
    description:
      "Charred yogurt-spiced chicken in tomato masala sauce with a measured serving of basmati rice.",
    ingredients: [
      "180g chicken breast",
      "180g cooked basmati rice",
      "150g tomato passata",
      "60g plain Greek yogurt",
      "1 tsp cooking oil",
      "Onion, garlic, ginger, and tikka spices",
      "Fresh coriander",
    ],
    calories: 720,
    protein: 52,
    carbs: 78,
    fat: 22,
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: "Medium",
    instructions: [
      "Coat the chicken in half the yogurt and tikka spices.",
      "Sear or grill the chicken until browned and nearly cooked.",
      "Cook onion, garlic, ginger, spices, and passata into a thick sauce.",
      "Finish the chicken in the sauce, stir in the remaining yogurt off the heat, and serve with rice.",
    ],
    tags: ["Dinner", "Indian", "Chicken", "Meal prep"],
  },
  {
    slug: "beef-keema-peas-rice",
    title: "Beef Keema with Peas & Rice",
    mealType: "Dinner",
    goals: ["High protein", "Meal prep"],
    description:
      "Spiced lean beef mince with peas, tomatoes, and basmati rice for a filling weeknight curry.",
    ingredients: [
      "150g lean beef mince",
      "180g cooked basmati rice",
      "80g peas",
      "120g chopped tomatoes",
      "1 tsp cooking oil",
      "Onion, garlic, ginger, cumin, and garam masala",
    ],
    calories: 700,
    protein: 43,
    carbs: 78,
    fat: 24,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: "Easy",
    instructions: [
      "Brown the mince with onion, garlic, and ginger.",
      "Add cumin, garam masala, and tomatoes, then simmer for 12 minutes.",
      "Stir in the peas and cook until tender.",
      "Serve with the measured basmati rice.",
    ],
    tags: ["Dinner", "Indian", "Beef", "Meal prep"],
  },
  {
    slug: "tandoori-chicken-roti",
    title: "Tandoori Chicken & Roti Plate",
    mealType: "Dinner",
    goals: ["High protein", "Get fit"],
    description:
      "Spiced tandoori chicken with roti, tomato-onion salad, and a cooling mint yogurt sauce.",
    ingredients: [
      "180g skinless chicken thighs",
      "1 medium wholewheat roti",
      "80g plain Greek yogurt",
      "Tomato, red onion, and lettuce",
      "Lemon juice and fresh mint",
      "Tandoori spices",
    ],
    calories: 650,
    protein: 50,
    carbs: 65,
    fat: 21,
    prepTimeMinutes: 15,
    cookTimeMinutes: 25,
    difficulty: "Medium",
    instructions: [
      "Coat the chicken in half the yogurt, lemon juice, and tandoori spices.",
      "Roast or grill until charred at the edges and cooked through.",
      "Mix the remaining yogurt with mint and prepare the tomato-onion salad.",
      "Serve the chicken with warm roti, salad, and mint yogurt.",
    ],
    tags: ["Dinner", "Indian", "Chicken", "High protein"],
  },
  {
    slug: "chana-spinach-curry-rice",
    title: "Chana Spinach Curry & Rice",
    mealType: "Dinner",
    goals: ["Budget", "Meal prep", "Balanced"],
    description:
      "A warming chickpea and spinach curry with enough rice to make it a satisfying dinner.",
    ingredients: [
      "220g cooked chickpeas",
      "170g cooked basmati rice",
      "100g spinach",
      "150g chopped tomatoes",
      "1 tsp cooking oil",
      "Onion, garlic, ginger, cumin, and garam masala",
    ],
    calories: 620,
    protein: 22,
    carbs: 100,
    fat: 15,
    prepTimeMinutes: 10,
    cookTimeMinutes: 25,
    difficulty: "Easy",
    instructions: [
      "Cook the onion, garlic, ginger, and spices in the oil.",
      "Add tomatoes and chickpeas, then simmer until thickened.",
      "Fold in the spinach until wilted.",
      "Serve with basmati rice and extra coriander if desired.",
    ],
    tags: ["Dinner", "Indian", "Vegetarian", "Budget"],
  },
  {
    slug: "lamb-rogan-josh-rice",
    title: "Lamb Rogan Josh & Rice",
    mealType: "Dinner",
    goals: ["Muscle gain", "High protein"],
    description:
      "Tender lean lamb in a deeply spiced tomato curry with a sensible basmati rice portion.",
    ingredients: [
      "170g lean lamb",
      "170g cooked basmati rice",
      "160g tomato passata",
      "50g plain Greek yogurt",
      "1 tsp cooking oil",
      "Onion, garlic, ginger, and rogan josh spices",
    ],
    calories: 760,
    protein: 44,
    carbs: 72,
    fat: 33,
    prepTimeMinutes: 15,
    cookTimeMinutes: 40,
    difficulty: "Medium",
    instructions: [
      "Brown the lamb in the oil and set it aside.",
      "Cook the onion, garlic, ginger, and spices until aromatic.",
      "Add passata and lamb, cover, and simmer until tender.",
      "Stir in the yogurt away from direct heat and serve with rice.",
    ],
    tags: ["Dinner", "Indian", "Lamb", "High protein"],
  },
  {
    slug: "boiled-eggs-fruit",
    title: "Boiled Eggs & Fruit",
    mealType: "Snack",
    goals: ["Quick protein", "Budget"],
    description: "A simple snack with protein and fruit.",
    ingredients: ["Boiled eggs", "Apple or banana"],
    calories: 240,
    protein: 13,
    carbs: 25,
    fat: 10,
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Boil eggs if needed.",
      "Serve with apple or banana.",
    ],
    tags: ["Snack", "Budget", "Simple"],
  },
  {
    slug: "apple-peanut-butter",
    title: "Apple with Peanut Butter",
    mealType: "Snack",
    goals: ["Simple snack", "Quick"],
    description: "A fast snack with fruit and healthy fats.",
    ingredients: ["Apple", "Peanut butter"],
    calories: 260,
    protein: 7,
    carbs: 30,
    fat: 14,
    prepTimeMinutes: 2,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Slice apple.",
      "Serve with peanut butter.",
    ],
    tags: ["Snack", "Quick", "Fruit"],
  },
  {
    slug: "protein-yogurt-cup",
    title: "Protein Yogurt Cup",
    mealType: "Snack",
    goals: ["Sweet snack", "High protein", "Quick"],
    description: "A sweet high-protein snack without much prep.",
    ingredients: ["Greek yogurt", "Honey", "Berries", "Cinnamon"],
    calories: 280,
    protein: 25,
    carbs: 32,
    fat: 5,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Add Greek yogurt to a cup.",
      "Add honey and berries.",
      "Finish with cinnamon.",
    ],
    tags: ["Snack", "Sweet", "High protein"],
  },
  {
    slug: "cottage-cheese-toast",
    title: "Cottage Cheese Toast",
    mealType: "Snack",
    goals: ["High protein", "Quick"],
    description: "A savory high-protein snack.",
    ingredients: ["Cottage cheese", "Wholegrain toast", "Tomato", "Pepper"],
    calories: 300,
    protein: 24,
    carbs: 32,
    fat: 8,
    prepTimeMinutes: 5,
    cookTimeMinutes: 2,
    difficulty: "Easy",
    instructions: [
      "Toast bread.",
      "Add cottage cheese.",
      "Top with tomato and pepper.",
    ],
    tags: ["Snack", "Savory", "High protein"],
  },
  {
    slug: "chicken-pepper-snack-plate",
    title: "Chicken Pepper Snack Plate",
    mealType: "Snack",
    goals: ["Lean snack", "Quick protein"],
    description:
      "A light snack plate with shredded chicken and crunchy vegetables.",
    ingredients: [
      "Shredded chicken breast",
      "Red pepper strips",
      "Mini tomatoes",
      "Greek yogurt dip",
      "Black pepper",
    ],
    calories: 300,
    protein: 30,
    carbs: 12,
    fat: 12,
    prepTimeMinutes: 10,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Add shredded chicken to a plate.",
      "Add red pepper and mini tomatoes.",
      "Add Greek yogurt dip.",
      "Season with black pepper.",
    ],
    tags: ["Snack", "Lean", "Quick protein"],
  },
  {
    slug: "smoothie-mini",
    title: "Smoothie Mini",
    mealType: "Snack",
    goals: ["Post-workout", "Quick", "High protein"],
    description: "A smaller smoothie for post-workout recovery.",
    ingredients: ["Milk", "Banana", "Greek yogurt", "Cinnamon"],
    calories: 350,
    protein: 25,
    carbs: 48,
    fat: 7,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Add all ingredients to blender.",
      "Blend until smooth.",
      "Serve cold.",
    ],
    tags: ["Snack", "Post-workout", "Smoothie"],
  },
  {
    slug: "biltong-apple-snack-box",
    title: "Biltong & Apple Snack Box",
    mealType: "Snack",
    goals: ["High protein", "Quick"],
    description:
      "Lean biltong with a crisp apple for a portable sweet-and-savoury snack.",
    ingredients: ["50g lean biltong", "1 medium apple"],
    calories: 230,
    protein: 25,
    carbs: 26,
    fat: 3,
    prepTimeMinutes: 2,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Portion the biltong into a container.",
      "Pack the apple whole or slice it just before eating.",
    ],
    tags: ["Snack", "Biltong", "Portable", "High protein"],
  },
  {
    slug: "biltong-cottage-cheese-bowl",
    title: "Biltong & Cottage Cheese Bowl",
    mealType: "Snack",
    goals: ["High protein", "Low carb", "Quick"],
    description:
      "A creamy, salty, high-protein snack bowl with biltong, cottage cheese, and fresh tomatoes.",
    ingredients: [
      "50g lean sliced biltong",
      "150g low-fat cottage cheese",
      "100g mini tomatoes",
      "Black pepper and smoked paprika",
    ],
    calories: 285,
    protein: 43,
    carbs: 12,
    fat: 7,
    prepTimeMinutes: 5,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Spoon the cottage cheese into a bowl and season with pepper and paprika.",
      "Top with sliced biltong and halved mini tomatoes.",
    ],
    tags: ["Snack", "Biltong", "Cottage cheese", "High protein"],
  },
  {
    slug: "biltong-hummus-crunch-plate",
    title: "Biltong Hummus Crunch Plate",
    mealType: "Snack",
    goals: ["High protein", "Get fit"],
    description:
      "Biltong, creamy hummus, and crunchy vegetables for a substantial afternoon snack.",
    ingredients: [
      "35g lean biltong",
      "60g hummus",
      "100g carrot sticks",
      "100g red pepper strips",
      "Paprika",
    ],
    calories: 305,
    protein: 24,
    carbs: 25,
    fat: 12,
    prepTimeMinutes: 7,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Spoon hummus onto a plate or into a small container.",
      "Add biltong, carrot, and red pepper.",
      "Dust the hummus lightly with paprika.",
    ],
    tags: ["Snack", "Biltong", "Vegetables", "High protein"],
  },
  {
    slug: "tuna-rice-cake-stack",
    title: "Tuna Rice-Cake Stack",
    mealType: "Snack",
    goals: ["High protein", "Quick"],
    description:
      "Crunchy rice cakes topped with a light tuna mix, tomato, and black pepper.",
    ingredients: [
      "100g tuna in spring water, drained",
      "3 plain rice cakes",
      "20g light mayonnaise",
      "80g sliced tomato",
      "Lemon juice and black pepper",
    ],
    calories: 250,
    protein: 26,
    carbs: 25,
    fat: 5,
    prepTimeMinutes: 6,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Mix the tuna with light mayonnaise, lemon, and pepper.",
      "Spoon onto the rice cakes and top with tomato.",
      "Eat immediately so the rice cakes stay crisp.",
    ],
    tags: ["Snack", "Tuna", "Crunchy", "High protein"],
  },
  {
    slug: "smoky-roasted-chickpeas",
    title: "Smoky Roasted Chickpeas",
    mealType: "Snack",
    goals: ["Budget", "Meal prep"],
    description:
      "Crunchy paprika-roasted chickpeas portioned for an affordable fibre-rich snack.",
    ingredients: [
      "120g cooked chickpeas, drained and dried",
      "1 tsp olive oil",
      "Smoked paprika",
      "Garlic powder",
      "Pinch of salt",
    ],
    calories: 245,
    protein: 11,
    carbs: 33,
    fat: 8,
    prepTimeMinutes: 5,
    cookTimeMinutes: 25,
    difficulty: "Easy",
    instructions: [
      "Pat the chickpeas very dry and toss with oil and seasonings.",
      "Roast at 200°C until crisp, shaking the tray halfway through.",
      "Cool completely before storing so they stay crunchy.",
    ],
    tags: ["Snack", "Budget", "Crunchy", "Meal prep"],
  },
  {
    slug: "frozen-yogurt-berry-bark",
    title: "Frozen Yogurt Berry Bark",
    mealType: "Snack",
    goals: ["Sweet snack", "Meal prep", "High protein"],
    description:
      "A cold, creamy yogurt bark with berries, honey, and a measured sprinkle of almonds.",
    ingredients: [
      "200g plain Greek yogurt",
      "80g mixed berries",
      "10g honey",
      "10g chopped almonds",
      "Vanilla extract",
    ],
    calories: 285,
    protein: 21,
    carbs: 32,
    fat: 8,
    prepTimeMinutes: 8,
    cookTimeMinutes: 0,
    difficulty: "Easy",
    instructions: [
      "Mix the yogurt with vanilla and spread it on a lined tray.",
      "Scatter over berries and almonds, then drizzle with honey.",
      "Freeze until firm and break into one serving of pieces.",
    ],
    tags: ["Snack", "Yogurt", "Sweet", "Meal prep"],
  },
];

export function getAllRecipes() {
  return recipes;
}

export function getRecipeBySlug(slug: string) {
  return recipes.find((recipe) => recipe.slug === slug) ?? null;
}

export function getRecipesByMealType(mealType: MealType) {
  return recipes.filter((recipe) => recipe.mealType === mealType);
}
